### ISSUE TITLE
Fine tuning BERT-NER on a domain-specific dataset

### ISSUE THREAD

**Issue by nzhiltsov** [kamalkraj/BERT-NER#10]
Hi @kamalkraj, nice work! I'm wondering how I can continue the training of a pre-trained CoNLL'03 BERT-NER model on a separate dataset? What POS tagger and chunker should I use to get proper train.text/valid.txt/test.txt files? How to start from the checkpoint and avoid the re-training of a model from scratch?

**Comment by kamalkraj** [comment]
@nzhiltsov 
You don't need POS tagger or chunker , for retraining on a different dataset . 
The model inputs are only tokenized text and corresponding NER tags .
For training on new dataset you have rewrite data loading part , you can load the weights from pre-trained model available on github. You have to initialize the final tagging layer depending on your new dataset .

**Comment by Anticsss** [comment]
@kamalkraj  so I have to have all the data should be in format...

EU B-ORG
rejects O
German B_MISC
call O
to O
boycott O
British B_MISC
lamb O
. O

right ?
if yes how can I tag particular token ?

**Comment by kamalkraj** [comment]
@Anticsss  
The data format you mentioned above is correct . you can use spacy gold for generating BILOU tags from entity offsets .
