### ISSUE TITLE
less supports in results

### ISSUE THREAD

**Issue by Icyzrw** [kamalkraj/BERT-NER#11]
Hi @kamalkraj, nice work ! It helps me a lot.
I'm wondering why the support of the valid dataset and test dataset results in this branch  is much smaller than the other branch in your results? 

I used your pretrained model in this dataset, but only get F1 = 0.9078 in test.txt.

**Comment by kamalkraj** [comment]
The results in master branch is wrong . I will update . there was bug in the evaluation code. Code is fixed now. so you may get different results than README
