### ISSUE TITLE
NER fails horribly when uncased

### ISSUE THREAD

**Issue by abhisaar** [kamalkraj/BERT-NER#15]
In the pre-trained example provided, try changing the casing in the sentence.

output = model.predict("**Steve** went to **paris**")
{'paris': {'tag': 'O', 'confidence': 0.9998948574066162},
 'Steve': {'tag': 'B-PER', 'confidence': 0.9998831748962402}}

output = model.predict("**steve** went to **Paris**")
{'Paris': {'tag': 'B-LOC', 'confidence': 0.9998199343681335}, 
'steve': {'tag': 'O', 'confidence': 0.9998823404312134}}

maybe training should be done uncased?

**Comment by kamalkraj** [comment]
@abhisaar 
Model trained as per original bert paper (cased)
You can experiment using uncased . Usually all the ner models have casing problem. Using Char level input in addition  to token level input solves this in a limited way. Current bert model only supports only token level inputs .
