### ISSUE TITLE
Cannot reproduce your reported F1 score

### ISSUE THREAD

**Issue by jind11** [kamalkraj/BERT-NER#18]
after downloading your pretrained model in the master branch and run this command:
'''
python run_ner.py --data_dir=data/ --bert_model=bert-base-cased --task_name=ner --output_dir=out --max_seq_length=128  --num_train_epochs 5 --do_eval --warmup_proportion=0.4
'''
I got the F1 score of 90.9 in the test set, which is far away from what you reported. Could you help with my issue? Thanks!

**Comment by sIncerass** [comment]
I run the same script and get the following:
```
precision    recall  f1-score   support

      PER     0.9619    0.9548    0.9584      1615
      ORG     0.8829    0.8989    0.8908      1661
      LOC     0.9250    0.9322    0.9286      1666
     MISC     0.7395    0.8248    0.7798       702
    [SEP]     1.0000    1.0000    1.0000         2

micro avg     0.8926    0.9155    0.9039      5646
macro avg     0.9001    0.9155    0.9075      5646
```

**Comment by kamalkraj** [comment]
@jind11 @sIncerass There is bug in the evaluation code of master branch . please use branch experiment, It also don't have extra `x` . Experiment branch is exact implementation of NER from the paper

**Comment by jind11** [comment]
hi, I ran your experimental branch and got this results:
 precision    recall  f1-score   support

      ORG     0.8754    0.9055    0.8902      1661
     MISC     0.7803    0.8348    0.8066       702
      LOC     0.9271    0.9305    0.9288      1668
      PER     0.9663    0.9573    0.9618      1617

micro avg     0.9031    0.9189    0.9109      5648
macro avg     0.9049    0.9189    0.9117      5648

It is still far from what the paper reported. It seems that the original paper cannot be reproduced, right?

**Comment by sIncerass** [comment]
@jind11 @kamalkraj I guess you can refer to https://github.com/allenai/allennlp/pull/2067#issuecomment-443961816, which explains a little bit about the similar issue for BERT NER reproduce.

**Comment by jind11** [comment]
@sIncerass based on your referenced issue, it looks to me that nobody but Devlin can ever get the results in the original paper, right? My group can only get something like 92.0.
