### ISSUE TITLE
Can't reproduce F1 scores

### ISSUE THREAD

**Issue by lxy444** [kamalkraj/BERT-NER#2]
After training the model using the default parameters, the result is
`             precision    recall  f1-score   support

        ORG     0.7019    0.7685    0.7337       337
        LOC     0.8190    0.8854    0.8509       419
       MISC     0.8188    0.8278    0.8233       273
        PER     0.7619    0.7453    0.7535       322

avg / total     0.7761    0.8113    0.7929      1351
`

which is different from the README results.

**Comment by kamalkraj** [comment]
default parameters ?
Can you share your cmd you used for training ?

**Comment by lxy444** [comment]
> default parameters ?
> Can you share your cmd you used for training ?

Yes, I used the default parameters.
`python run_ner.py --data_dir=data/ --bert_model=bert-base-cased --task_name=ner --output_dir=out --max_seq_length=128 --do_train --num_train_epochs 5 --do_eval --warmup_proportion=0.4`

Also, theres is a file named model_config.json in the out folder, which contains
`{"bert_model": "/mnt/data/share_data/nlp/bert/model/cased_L-12_H-768_A-12", "do_lower": false, "max_seq_length": 128, "num_labels": 13, "label_map": {"1": "O", "2": "B-MISC", "3": "I-MISC", "4": "B-PER", "5": "I-PER", "6": "B-ORG", "7": "I-ORG", "8": "B-LOC", "9": "I-LOC", "10": "X", "11": "[CLS]", "12": "[SEP]"}}
`

**Comment by kamalkraj** [comment]
I trained on different machines results are only varying by ~0.3
For now you can use pretrained model , Link in Readme
