### ISSUE TITLE
Alternative for CUDA

### ISSUE THREAD

**Issue by Rajput245** [kamalkraj/BERT-NER#20]
Hey @kamalkraj , thanks for your work.
I am trying to run this code on my AMD Vega 10 XT. Is there any way you can help me because your code is on CUDA.
Thnaks in advance.

**Comment by kamalkraj** [comment]
@Rajput245 
Try installing pytorch for AMD gpu
https://github.com/ROCmSoftwarePlatform/pytorch/issues/337#issuecomment-467354835
Pytorch API doesn't have any change on GPU type. So you can use the same code
