### ISSUE TITLE
Reasons for predicting the labels of [CLS] and [SEP]?

### ISSUE THREAD

**Issue by Dongfeng-He** [kamalkraj/BERT-NER#21]
Hi, thanks for your great job.
I have a question here, why do you predict the labels of [CLS] and [SEP] rather than simply mask them? Will it improve the performance of the NER task?

**Comment by kamalkraj** [comment]
Hi @Dongfeng-He 
I tried predicting start([CLS]) and end([SEP]) tokens as `<PAD>` and `O` .  There is no improvement on the model F1 score. So I kept the start and end as `[CLS]` and `[SEP]`

**Comment by Dongfeng-He** [comment]
Thanks, kamalkraj!

**Comment by zhiyuanpeng** [comment]
> Hi @Dongfeng-He I tried predicting start([CLS]) and end([SEP]) tokens as `<PAD>` and `O` . There is no improvement on the model F1 score. So I kept the start and end as `[CLS]` and `[SEP]`

Hi Kamalkraj,
If you predict CLS and SEP, how to make sure valide tokens (non CLS and SEP tokens) will be not predicted as SEP or CLS. WIth seqeval==1.2.2, I find the 'SEP]' is in the predicted labels. I masked the CLS and SEP which means the two tokens will not contribute to the loss and I find I can only got F1 0.905 on test dataset while I run your code and got F1 0.911

**Comment by BCWang93** [comment]
> Hi @Dongfeng-He I tried predicting start([CLS]) and end([SEP]) tokens as `<PAD>` and `O` . There is no improvement on the model F1 score. So I kept the start and end as `[CLS]` and `[SEP]`

hi, I see you caculate loss in training use [cls] and [sep], this method get great result? if I tokened is to <pad>, this will not calculate loss, did you try this method? Thanks!
