### ISSUE TITLE
warmup_linear - issue 

### ISSUE THREAD

**Issue by niranjan8129** [kamalkraj/BERT-NER#22]
Hi, Thank you sharing the model . I  am getting an error while training the model .
Getting warmup_linear library is not available .

Could you please help me how to solve this issue ?

Regards,
niranjan 

line no 507:
lr_this_step = args.learning_rate * warmup_linear(global_step/num_train_optimization_steps, args.warmup_proportion)

**Comment by kamalkraj** [comment]
Hi @niranjan8129,
Did you install the requirements from the repo?

**Comment by vikas95** [comment]
Hi Kamal,

Thanks for sharing the codes, these are very well written and easy to understand. 

I wanted to follow up on this error as I am getting a similar error:

 File "/usr/local/lib/python3.7/site-packages/pytorch_pretrained_bert/optimization.py", line 148, in step
    lr_scheduled = group['lr'] * schedule_fct(state['step']/group['t_total'], group['warmup'])
ZeroDivisionError: float division by zero



I wanted to mention that I am training the model on a separate NER dataset which is nearly (1/4)th the size of CoNLL 03 dataset. I am using the same hyper parameter as you have suggested in the readme file but I am suspecting we have to adjust batch size or other related hyper parameters for fixing this error. 

I am working on this but if you have seen this error before, can you suggest any quick fix ??

Looking forward for your response,

Thanks

**Comment by kamalkraj** [comment]
Hi @vikas95 ,
Try using the latest code in `dev` branch
