### ISSUE TITLE
what is the 'valid_positions' meaning?

### ISSUE THREAD

**Issue by Chriszhangmw** [kamalkraj/BERT-NER#24]
from the original paper, the inputs contains three parameters, they are input_ids,input_mask,segment_ids, but I saw your code including valid_positions which is difficult for me to understand, can you expalin that for me?  thanks

**Comment by kamalkraj** [comment]
Hi @Chriszhangmw,
If you look at the paper for ner label prediction they only consider the first token split from the tokenized word.  
![Screenshot 2019-07-22 at 12 21 20 PM](https://user-images.githubusercontent.com/17096858/61612137-462fbf80-ac7b-11e9-8ae0-332efffdd512.png)
valid_positions contains those first token positions.

**Comment by Chriszhangmw** [comment]
hey， thanks， I have check the original paper again, but still cannot find that, can you send me the paper or blog you post?  many thanks
![image](https://user-images.githubusercontent.com/52879076/61614381-2bb70f80-ac96-11e9-9934-111a729e446f.png)

**Comment by Chriszhangmw** [comment]
zhangmw_play@163.com   my email account.

**Comment by kamalkraj** [comment]
@Chriszhangmw https://arxiv.org/pdf/1810.04805v1.pdf
Section 4.3
