### ISSUE TITLE
The readfile() function does not return output as the suggested format

### ISSUE THREAD

**Issue by lcthw** [kamalkraj/BERT-NER#29]
https://github.com/kamalkraj/BERT-NER/blob/48a868b4ccadffee4b0a5c752f95a78bb62ef8f9/run_ner.py#L116

To begin with, thank you very much for sharing the code, it did save me a huge amount of time!

The if statement in line 116 should be in the for loop above, otherwise the output would be a list of tuples of a list of a sentence followed by a list of its corresponding tags eg: 

> (['-', 'JAPAN', 'GET', 'LUCKY', 'WIN', ',', 'CHINA', 'IN', 'SURPRISE', 'DEFEAT', '.'],
  ['O', 'B-LOC', 'O', 'O', 'O', 'O', 'B-PER', 'O', 'O', 'O', 'O']),
 (['Nadim', 'Ladki'], ['B-PER', 'I-PER']),
 (['AL-AIN', ',', 'United', 'Arab', 'Emirates', '1996-12-06'],
  ['B-LOC', 'O', 'B-LOC', 'I-LOC', 'I-LOC', 'O'])]

If the desired output is as suggested in the code, i.e. 

> [ ['EU', 'B-ORG'], ['rejects', 'O'], ['German', 'B-MISC'], ['call', 'O'], ['to', 'O'], ['boycott', 'O'], ['British', 'B-MISC'], ['lamb', 'O'], ['.', 'O'] ]

then the if statement could be modified as:
`if len(sentence) > 0:
            sentence.extend(label);
           data.append(sentence);
            sentence = [];
            label = []`

**Comment by kamalkraj** [comment]
Hi @FatPupp,
The output format of readfile function is not exactly the one mentioned in the comments. I copied the readfile from one of my older projects. There I was using that format. I removed comments to avoid confusion. 
Thanks
