### ISSUE TITLE
NER on a document

### ISSUE THREAD

**Issue by sandeeppilania** [kamalkraj/BERT-NER#30]
Thanks Kamal for wonderful work.

I am seeking for some help on how can i keep a check on the co reference of entities in a doc. For exam Person names as James Paul appears 10 times in the document ( which can be any one of James or Paul or James Paul). Can you suggest me some ideas on how to list up all the mentions together. It can get tricky if the doc has like two person as James Paul and James Real so how would one can find which James is being referred in the doc.

Sorry, just looking for some help

Thanks

**Comment by gui-li** [comment]
> Thanks Kamal for wonderful work.
> 
> I am seeking for some help on how can i keep a check on the co reference of entities in a doc. For exam Person names as James Paul appears 10 times in the document ( which can be any one of James or Paul or James Paul). Can you suggest me some ideas on how to list up all the mentions together. It can get tricky if the doc has like two person as James Paul and James Real so how would one can find which James is being referred in the doc.
> 
> Sorry, just looking for some help
> 
> Thanks

At first, you should have such rich-annotated data to get this work don't. It's not only the work of NER, because most of the NER dataset only annotate the appearance of entity without their inner relationship.
