### ISSUE TITLE
Dataset compatile issue

### ISSUE THREAD

**Issue by gui-li** [kamalkraj/BERT-NER#33]
Can I use my own dataset with the similar format with conll2003 which only have word and tag? And the tag is different to the conll2003 but still comply to IOB2.

**Comment by kamalkraj** [comment]
Hi @gui-li,
You can use own dataset in the format of conll2003 . But change the list of tags in [get_labels](https://github.com/kamalkraj/BERT-NER/blob/ee25c1403c08a9e897b662f59da416ca5c919235/run_ner.py#L159)

**Comment by gui-li** [comment]
Thank you. And the pos and other tag in conll2003 can be omitted right? Keep the entity tag only?

**Comment by gui-li** [comment]
elif label_ids[i][j] == 11:
at line 576 in run_ner.py should also be modified accourding to custom tag.
