### ISSUE TITLE
wordpiece and label?

### ISSUE THREAD

**Issue by xuanzebi** [kamalkraj/BERT-NER#37]
the latest versions about wordpiece and label is   Jim Hen ##son was a puppet ##eer    [Jim , Hen , was , a, puppet]?

only get first token about a word which is tokenizer by wordpiece?

have you get other methods to do experimental comparison?
Hope for you reply ^^ 
Thanks

**Comment by xuanzebi** [comment]
![image](https://user-images.githubusercontent.com/26642184/63862991-15604a00-c9e0-11e9-8685-8282e62dab92.png)
in this code ?          len(tokens)!= len(labels)
For example 
tokens : Jim Hen ##son was a puppet ##eer 
label:  I-PER I-PER  O O O
 
so i am confused how to deal it?

**Comment by kamalkraj** [comment]
Hi @xuanzebi ,
length of `tokens` is not equal to length of `labels`
tokens contain all the tokens from wordpiece tokenization . But labels are available only for the first split of each token. All tokens are needed for feature extraction from bert. After extracting features from bert, the only first split of a token is considered and that length is equivalent to length of labels. That you can check in the forward function of model

**Comment by xuanzebi** [comment]
Thanks ^
I want to ask that this method is better method to deal this problem?
