### ISSUE TITLE
I want to ask how much time cost to fine tune conll03 task?

### ISSUE THREAD

**Issue by xuanzebi** [kamalkraj/BERT-NER#39]
i spent few minutes to fine tune on conll03 task?
so i think i was wrong with somewhere.

**Comment by gui-li** [comment]
It depends on your computational resources and setting of hyperparameter. As for me, I spent nearly an hour with default hyperparameter on a machine with 8 tesla v100s.

**Comment by kamalkraj** [comment]
@xuanzebi @gui-li 
configuration: 
GPUs : 4 x Titan RTX 24GB
CPU : i9-9900k
Cuda : 10.0
Torch : 1.2.0

`Bert-base-cased`: 7 minutes/epoch
`Bert-large-cased`: 13 minutes/epoch

**Comment by xuanzebi** [comment]
Thanks
