### ISSUE TITLE
Performance and fine-tuning custom NER

### ISSUE THREAD

**Issue by Rao2321** [kamalkraj/BERT-NER#40]
Hey, I would like to know how fast were your predictions for a single request with multiple entities? And did you perform any load testing, if so what are the results?
Also I would like to know approaches for fine-tuning a custom NER model using BERT. If you know any approaches, please help me. 
Thanks.

**Comment by gui-li** [comment]
@Rao2321 As for NER on custom dataset you must annotate data on yourself and do some process to align your data format with conll2003. As for the annotation tool, you can choose brat, profigy, and YEDDA. Brat requires some steps to deploy and it has strict requirement on data format. Prodigy is not free, I didn't try it. YEDDA is a light weight fast annotation tool, but it's not versatile as other annotation tools. And you can check doccano on github, it's a new annotation tool.

**Comment by kamalkraj** [comment]
@Rao2321 
time for prediction:
`BERT-BASE`
![Screenshot 2019-09-19 at 12 41 20 PM](https://user-images.githubusercontent.com/17096858/65221652-16663200-dadb-11e9-8a70-767a634d5913.png)
`BERT-LARGE`
![Screenshot 2019-09-19 at 12 41 09 PM](https://user-images.githubusercontent.com/17096858/65221678-1d8d4000-dadb-11e9-8fe9-48d600d63d67.png)
