### ISSUE TITLE
Evaluation does not use GPU

### ISSUE THREAD

**Issue by sajastu** [kamalkraj/BERT-NER#43]
Hi, just figured it out. Inference with python does not get onto GPU. It seems that it just uses CPU. How can we push it into GPU? Is there any option to do so? Or it's not been implemented?

Thanks!

**Comment by kamalkraj** [comment]
Hi @sajastu ,
Fixed 6286a475b3f85ad595f37b27d1e0d2a31e6edf70
Model will moved to GPU/CPU , depends on the `cuda` device availablity on the env.
