### ISSUE TITLE
UserWarning:Was asked to gather along dimension 0, but all input tensors were scalars;

### ISSUE THREAD

**Issue by lichunnan** [kamalkraj/BERT-NER#46]
Hey,
    as the tittle,And training stopped at 12% .How can i deal with this situation
![image](https://user-images.githubusercontent.com/33343461/66578908-85045000-ebae-11e9-8d15-51e34c93c0d7.png)

**Comment by lichunnan** [comment]
Full training information
![image](https://user-images.githubusercontent.com/33343461/66579610-aa458e00-ebaf-11e9-9276-e71a136e3ed9.png)

**Comment by kamalkraj** [comment]
Hi @lichunnan ,
Could try training in single GPU ?
