### ISSUE TITLE
Just a question 

### ISSUE THREAD

**Issue by ghost** [kamalkraj/BERT-NER#48]
Hello , 
finally, excellent script for bert-NER. I am just wondering if this script can be used(slight changes) to train a token based classification task. i.e. similar to NER task but the token(target word) to be classified are given in advance. For example, train a model for word-sense disambiguation. Given a word in a sentence determine/classify its sense. 
e.g. "He went to the store" went here has sense “motion”. the target word here is "went"
Any idea?

**Comment by kamalkraj** [comment]
Hi @moh55m55 ,
You can modify this NER code to fit into your task.
Input the word you want to classify as sentence B. And connect classification layer to `[CLS]` token

**Comment by ghost** [comment]
Thanks for your reply, 
I got it.

**Comment by ghost** [comment]
Well, just to follow up on your idea. What if I have two exact words in the same sentence with different senses to classify?  is there a way to add the position? 
Thanks

**Comment by kamalkraj** [comment]
@moh55m55 
![IMG_20191110_174450](https://user-images.githubusercontent.com/17096858/68543791-cbcdab80-03e1-11ea-85ae-822158296404.jpg)
predict sense per token , Sentence B = word you want to predict

**Comment by ghost** [comment]
For example, in this sentence, "After I sat on on the bank of the river,  I went to the bank to cash a check"  

 if I  i understand it, the input sequence for the first bank : 
A= the sentence [sep] bank
B=  bank 
label = the label 

And  the input sequence for the second bank is the same

is that right? 

Thanks for your help.

**Comment by kamalkraj** [comment]
The first suggested method won't be able to handle the same word appearing more than once in an example.
Your input method mention in the above comment is correct. 

For handling same word appearing multiple times in an example, change problem as a sequence tagging. You will input which word to be tagged as sentence B.  refer to img i shared in previous comment.
