### ISSUE TITLE
How to use BERT just for ENTITY extraction from a Sequence without classification in the NER task?

### ISSUE THREAD

**Issue by ManojPrabhakar** [kamalkraj/BERT-NER#49]
My requirement here is given a sentence(sequence), I would like to just extract the entities present in the sequence without classifying them to a type in the NER task. I see that BertForTokenClassification for NER does the classification. Can this be adapted for just the extraction?

Can you give me an idea of how to do **entity extraction/identification using BERT?**

**Comment by kamalkraj** [comment]
Hi @ManojPrabhakar,
Yes, you can use  BertForTokenClassification for just extraction. 
Initialize the  BertForTokenClassification  with  only one entity and train

Example tags:
[ 'O' , B-ENT, I-ENT, '[CLS]', '[SEP]' ]

**Comment by ManojPrabhakar** [comment]
@kamalkraj Thank you!! 
I will try that.
