### ISSUE TITLE
N-Gram support

### ISSUE THREAD

**Issue by gittb** [kamalkraj/BERT-NER#50]
Hey Kamal,
Great work on the repo and major thanks for hosting the trained model.

Would it be possible to add N-Gram support to this model, for say, 'New York' instead of detecting on 'New' and then 'York'?

Also, any plans to train a larger model for QA or NER? Say RoBERTa or XL-NET?

**Comment by kamalkraj** [comment]
Hi @gittb,
N-Gram support https://github.com/kamalkraj/BERT-NER/issues/8
Model is designed to output as CoNLL tags

But you can join `[ New , York ]` `[ B-LOC , I-LOC ]` --> `[ New York]` `[ LOC ]` 

Larger models , maybe next month

**Comment by gittb** [comment]
By joining, do you mean manual post-processing?

The main reason I was curious is if I am using NER as more of a service to analyze incoming documents, I would want to know if a place is 'New York' automatically

I guess you could do this by looking for sequential similar tags but that could be problematic...

Any thoughts?

**Comment by gittb** [comment]
Also, where would I find a document detailing what all of the labels mean?

**Comment by kamalkraj** [comment]
Hi @gittb,
joining is manual pos-processing. Labels in this NER:
 ["O", "B-MISC", "I-MISC",  "B-PER", "I-PER", "B-ORG", "I-ORG", "B-LOC", "I-LOC"]

https://www.clips.uantwerpen.be/conll2003/ner/

**Comment by gittb** [comment]
That is all I need to know! Thank you very much
