### ISSUE TITLE
About valid_output

### ISSUE THREAD

**Issue by Anikacyp** [kamalkraj/BERT-NER#53]
When I read the code, I have concerns with the following part:
for i in range(batch_size):
            jj = -1
            for j in range(max_len):
                    if valid_ids[i][j].item() == 1:
                        jj += 1
                        valid_output[i][jj] = sequence_output[i][j]

why the valid_output is valid_output[i][jj], not valid_output[i][j]? Can you help me explain it? 

Thanks.

**Comment by kamalkraj** [comment]
Hi @Anikacyp,
valid_output is initialized with zeros in the same shape as sequence_output.
So what happens in the for loop is:
in first for loop, I am getting a single example from the batch : sequence_output[i] (shape: (max_len,feat_dim)
in the second loop, I am getting a single word from a sentence: sequence_output[i][j] (shape:(1,feat_dim))

valid_output contains the only words that are valid. valid words mean, the first-word segment from 
the tokenizer.

![Screenshot 2019-11-04 at 3 03 10 PM](https://user-images.githubusercontent.com/17096858/68111087-54e17000-ff14-11e9-8826-6e481026ae0a.png)
so valid_ouput index `jj` is incremented only when valid_ids == 1
`j` is the index of current token in the iteration

**Comment by Anikacyp** [comment]
Hi @kamalkraj ,

Thanks for your reply, I understand why to rewrite the sequence_output to valid_output.
What confused me is that why use jj not j as the second index of valid_output.

Take the following sentence as an example to illustrate:
![Screenshot 2019-11-04 at 3 03 10 PM](https://user-images.githubusercontent.com/17096858/68111087-54e17000-ff14-11e9-8826-6e481026ae0a.png)

it should have 7 embeddings for the above sentences.  the valid_output want filter ##son and ##eer out, right?

_jj_ started from -1, with the code, _**Jim**_ and _**Hen**_ would get the original sequence_output, **_##son_** would get the initial value 0. And next, _**was**_ is a valid output, but it gets _jj_=2 which is the sequence_output[i][j], i.e. _**##son**_, is it correct? or I misunderstand it?

**Comment by kamalkraj** [comment]
@Anikacyp 
`##son` is not passed to valid_output
https://arxiv.org/pdf/1810.04805v1.pdf 
"To make this compatible with WordPiece tokenization, we feed each CoNLL-tokenized input word into our WordPiece tokenizer and use the hidden state corresponding to the first sub-token as input to the classifier. " 
![IMG_20191104_160608](https://user-images.githubusercontent.com/17096858/68115044-798e1580-ff1d-11e9-89c3-2da19b3cbc5a.jpg)

**Comment by Anikacyp** [comment]
@kamalkraj clear explanation, Thanks very much!
