### ISSUE TITLE
suggestion for own dataset to train on  pretrained model.

### ISSUE THREAD

**Issue by vigneshgig** [kamalkraj/BERT-NER#54]
Thanks, for the great project.
I checked the train format.
it contains text, pos , bio-tag, entity tag(bio-schema)
for example:
-DOCSTART- -X- -X- O

EU NNP B-NP B-ORG
rejects VBZ B-VP O
German JJ B-NP B-MISC
call NN I-NP O
to TO B-VP O
boycott VB I-VP O
British JJ B-NP B-MISC
lamb NN I-NP O
. . O O
I having a 10,000 own sentence data, I can do entity tagging for my dataset. but How can i do pos and bio-tag is there any python library especially for bio-tag.

Thanks

**Comment by kamalkraj** [comment]
Hi @vigneshgig,
You can use [doccano](https://github.com/chakki-works/doccano) for data tagging. 
Fill `O` for pos to maintain data structure, pos features are not used for this model.

**Comment by vigneshgig** [comment]
Thanks for the  quick reply @kamalkraj then what about bio-tag B-NP,B-VP.
To train, i have  to run the below command line
python run_ner.py --data_dir=data/ --bert_model=bert-base-cased --task_name=ner --output_dir=out_base --max_seq_length=128 --do_train --num_train_epochs 5 --do_eval --warmup_proportion=0.1
is this command line start training from the pretrained model or from scratch.
I want to train the my own data in pretrained model.
is there any guide link

**Comment by kamalkraj** [comment]
For Fine Tuning
```bash
python run_ner.py --data_dir=data/ --bert_model=bert-base-cased --task_name=ner --output_dir=out_base --max_seq_length=128 --do_train --num_train_epochs 5 --do_eval --warmup_proportion=0.1
```
Data folder must contain atleast train file.

About Data Tagging:
Actually, data in below format is supported:
```
EU B-ORG
rejects O
German B-MISC
call O
to O
boycott O
British B-MISC
lamb O
. O
```
The data reader, read only the first token and last token in a line of dataset. So you don't need to provide 2 other tags.

**Comment by vigneshgig** [comment]
Thanks @kamalkraj

**Comment by vigneshgig** [comment]
@kamalkraj  is DOCSTART is compulsory

**Comment by kamalkraj** [comment]
@vigneshgig 
No
