### ISSUE TITLE
Loading Bert

### ISSUE THREAD

**Issue by pierre-zhao** [kamalkraj/BERT-NER#55]
I have download pre-trained bert model from [here](https://h5yeya.bn.files.1drv.com/y4m2MNHwEN7mspOAAsZwOmSeZEkwunW7Ai53sayxDoL9ae8FecNXB3Q-dRiXEK8mw74qGLBgA1leSv5OJ4GAetCN3909NXhgzHM8pYujWMMfALl8otpRsG-oMWOyzMbhCAFbgs75tAqkbWUkeqvEMOg5GMlNCcR0ddHqSn3-YNyJ7l68YJja6pWx0O5t8K4wEf1XJQavM-W_judTq-TTIXrAQ/base.zip?download&psid=1
) and unzip it to BERT-NER/bert-base-cased.
But when I begin to train the new model using your code, the pytorch_transformers can not successfully load bert.  The log  is posted here:
11/12/2019 22:23:06 - INFO - pytorch_transformers.file_utils -   https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-pytorch_model.bin not found in cache or force_download set to True, downloading to /tmp/tmptak_42kp

**Comment by kamalkraj** [comment]
for training, a new model original weights should be present in your machine. It will be automatically downloaded and cached.

**Comment by kamalkraj** [comment]
[here]() you posted is not accessible to me.@pierre-zhao

**Comment by pierre-zhao** [comment]
Hello,
I figure it out now. The reason is the route of pre-trained model. When I type the full path ('~/bert-base-cased') rather than 'bert-base-cased' behind --bert_model, it works.
