### ISSUE TITLE
How to make use of the pretained weights from download link?

### ISSUE THREAD

**Issue by deepitapai** [kamalkraj/BERT-NER#6]
Hi! Thanks for your work. I'm trying to run the model on my train-test-valid set using pre-trained weights from your google drive link but I don't see the right parameters to give when calling run_ner script.

**Comment by kamalkraj** [comment]
@deepitapai 
After downloading weight files to this repo folder ,Follow instructions on [here](https://github.com/kamalkraj/BERT-NER#inference)
You don't need to run `run_ner.py` for inference

**Comment by alexferrari88** [comment]
> @deepitapai
> After downloading weight files to this repo folder ,Follow instructions on [here](https://github.com/kamalkraj/BERT-NER#inference)
> You don't need to run `run_ner.py` for inference

stupid question coming...
if I installed the repo via pip, in which folder should I put the weight files?

**Comment by kamalkraj** [comment]
@alexferrari88 
What you mean by installed repo by pip ? did you clone the repo and installed the requirements ?
put the weight files in repo folder

**Comment by alexferrari88** [comment]
> @alexferrari88
> What you mean by installed repo by pip ? did you clone the repo and installed the requirements
> put the weight files in repo folder

Sorry, you're right, I got confused! I put the weights in the "out" folder in the repo folder but now I get this error: FileNotFoundError: [Errno 2] No such file or directory: 'out/config.json'

Makes sense because in the folder, the weights are called "bert_config.json". How can I change that?
