### ISSUE TITLE
mBERT for multilingual NER

### ISSUE THREAD

**Issue by pascalhuszar** [kamalkraj/BERT-NER#67]
Great Repo!
I'm currently working on a German NER system and want to investigate how German-related languages (Germanic languages) could improve such a system.
Question(s): Is it possible to use mBERT in this project? How long (approx.) does it take to train such a model with German dataset and also different languages.

Greetings.
Pascal

**Comment by Rajmehta123** [comment]
Did you train using mbert? If yes, can you share the pre-trained model?
