### ISSUE TITLE
Problems with installing req

### ISSUE THREAD

**Issue by pascalhuszar** [kamalkraj/BERT-NER#69]
While installing the requiremnts via cmd or even in pycharm this error occurs
`ERROR: Could not find a version that satisfies the requirement torch==1.2.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)`
Tried it with conda, didnt work.

Any help or hints?!

**Comment by kamalkraj** [comment]
upgrade pip to the latest version
