### ISSUE TITLE
How to identify entities made of more that 1 word?

### ISSUE THREAD

**Issue by alexferrari88** [kamalkraj/BERT-NER#8]
Hi, I would like to recognize entities that are made up of more than one word: e.g.

- Stephen King

- The Art of War

- United States of America

etc...

Your program splits each word making this impossible. Any workaround for this?

**Comment by kamalkraj** [comment]
![Screenshot 2019-05-17 at 6 59 31 PM](https://user-images.githubusercontent.com/17096858/57931415-0a245b00-78d6-11e9-8638-c5a846000236.png)
