### ISSUE TITLE
Label [SEP] in results

### ISSUE THREAD

**Issue by mcfly5** [kamalkraj/BERT-NER#9]
If use the small --max_seq_length (in example bellow 32), we get SEP in results.
The lower max_seq_length the greater SEPs 

             precision    recall  f1-score   support
        LOC     0.9248    0.9248    0.9248      1529
        PER     0.9556    0.9582    0.9569      1436
        ORG     0.8860    0.8993    0.8926      1539
       MISC     0.7620    0.8242    0.7919       637
      [SEP]     1.0000    1.0000    1.0000       637

avg / total     0.9125    0.9235    0.9178      5778

**Comment by kamalkraj** [comment]
which branch are you using @mcfly5

**Comment by mcfly5** [comment]
I use master

**Comment by sandeeppilania** [comment]
which branch to use to avoid [SEP] tags. I used experiment and i am get those extra [SEP] tags. So, would you recommend to use master instead !

**Comment by kamalkraj** [comment]
@sandeeppilania 
what is max_seq_length you are using?

**Comment by sandeeppilania** [comment]
i used the pretrained models from your drive and for both out and out=!X i am getting assertion error because of extra [SEP]

**Comment by kamalkraj** [comment]
@sandeeppilania Could you share the input sample you are trying , so that i can reproduce the issue

**Comment by sandeeppilania** [comment]
@kamalkraj Here it the sample  -  
model = Ner("out_!x")
output = model.predict("Sandeep went to Paris")

and these are the labels and words list followed by which i get assertion error
['Sandeep', 'went', 'to', 'Paris']
['B-PER', 'O', 'O', 'B-LOC', '[SEP]']

**Comment by kamalkraj** [comment]
ec7f643c679649bbd9e71ccde0528dd3e8ef5757
Bug fixed
